### ISSUE TITLE
Choose a backend stack

### ISSUE THREAD

**Issue by Globidev** [GavoTrav/subsunday#2]
⚠️ Vote only if you think you will be involved in the development of the **backend**

### Programming language

The open-source aspect of the project should be a major factor in the decision of what programming language we choose: **the ability for new contributors to maintain the code**. 
At the moment, the backend logic seems simple enough that we don't really have to worry about performance. 
That is why I would recommend choosing a popular and easy to use language. 
I deliberately restricted the amount of choices and based them on what the active members of the Discord's #coding channel seem to be comfortable with. 
If you choose `Other` or disagree with my reasoning, please elaborate in a comment/on Discord.

http://www.strawpoll.me/13711847

### Datastore

We will most likely need some kind of datastore (at least for the votes).
The requirement seems very simple for now and maybe a simple key-value store like [Redis](https://redis.io/) is enough ?
Or maybe it might not be resilient enough to requirements' changes ?
You tell me what you think.

http://www.strawpoll.me/13711862

### Webserver

It's usually a good idea to use a proven webserver as an entrypoint for incoming requests.

http://www.strawpoll.me/13711868

**Comment by GavoTrav** [comment]
#6
