### ISSUE TITLE
Choose a frontend stack for the website

### ISSUE THREAD

**Issue by Globidev** [GavoTrav/subsunday#3]
⚠️ Vote only if you think you will be involved in the development of the **frontend**

### Programming language

The language used will obviously have to target javascript (ok, true, there is also webassembly now)
With the same maintainability concerns expressed in #2 I think it would be wiser to not wander too far away from Javascript and its supersets.
If you choose `Other`, please elaborate in the comments.

http://www.strawpoll.me/13712147

### Framework / Libraries

It seems hard to architect modern client-side applications without using a framework nowadays, but some may think it's overkill for this project ?
I only listed the two most popular ones, feel free to check `Other` and try to convince people here to use your favorite shiny toy.

http://www.strawpoll.me/13712181

**Comment by GavoTrav** [comment]
#6
